# Generated by Django 5.1 on 2024-09-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_bot_token",
            field=models.CharField(
                default="", max_length=150, verbose_name="Telegram Bot токен"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram_chat_id",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Telegram chat id"
            ),
        ),
    ]
