# Generated by Django 5.1 on 2024-09-10 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_telegram_bot_token_user_telegram_chat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="telegram_chat_id",
        ),
    ]
