# Generated by Django 5.1 on 2024-09-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spa", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.CharField(
                choices=[
                    ("DISABLE", "Отключено"),
                    ("EVERY_DAY", "Ежедневно"),
                    ("EVERY_WEEK", "Еженедельно"),
                ],
                default="DISABLE",
                max_length=30,
                verbose_name="периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                default="", max_length=150, verbose_name="Вознаграждение"
            ),
        ),
    ]
