# Generated by Django 5.1 on 2024-09-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spa", "0002_alter_habit_period_alter_habit_reward"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="date_time_next_sent",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата и время следующего оповещения",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="period",
            field=models.CharField(
                choices=[
                    ("DISABLE", "Отключено"),
                    ("EVERY_MINUTE", "Ежеминутно"),
                    ("EVERY_HOUR", "Ежечасно"),
                    ("EVERY_DAY", "Ежедневно"),
                    ("EVERY_WEEK", "Еженедельно"),
                ],
                default="DISABLE",
                max_length=30,
                verbose_name="периодичность",
            ),
        ),
    ]
